"""init7

Revision ID: 23ee43f59de3
Revises: ff802336ff3e
Create Date: 2025-03-10 15:57:17.297736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23ee43f59de3'
down_revision: Union[str, None] = 'ff802336ff3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_documents', sa.Column('date_bind', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract_documents', 'date_bind')
    # ### end Alembic commands ###
