"""init4

Revision ID: 37ce0d029553
Revises: c018ea38772d
Create Date: 2025-03-09 16:52:10.683307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37ce0d029553'
down_revision: Union[str, None] = 'c018ea38772d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract',
    sa.Column('con_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('con_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('con_id')
    )
    op.add_column('contract_documents', sa.Column('con_doc_id', sa.Integer(), nullable=False))
    op.add_column('contract_documents', sa.Column('document_id', sa.Integer(), nullable=False))
    op.drop_constraint('contract_documents_email_fkey', 'contract_documents', type_='foreignkey')
    op.create_foreign_key(None, 'contract_documents', 'contract', ['contract_id'], ['con_id'])
    op.create_foreign_key(None, 'contract_documents', 'documents', ['document_id'], ['doc_id'])
    op.drop_column('contract_documents', 'email')
    op.drop_column('contract_documents', 'name')
    op.add_column('documents', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'user_id')
    op.add_column('contract_documents', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('contract_documents', sa.Column('email', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'contract_documents', type_='foreignkey')
    op.drop_constraint(None, 'contract_documents', type_='foreignkey')
    op.create_foreign_key('contract_documents_email_fkey', 'contract_documents', 'documents', ['email'], ['doc_id'])
    op.drop_column('contract_documents', 'document_id')
    op.drop_column('contract_documents', 'con_doc_id')
    op.drop_table('contract')
    # ### end Alembic commands ###
